language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TYPO3_VERSION=^8 COVERAGE=1
    - php: 7.2
      env: TYPO3_VERSION=^8
env:
  global:
    secure: S8QheEMVpSRsPPIhYQZ4tUCTbxpM7csZ0GydJaPY8p/FAEnZLiH6xcsiTGKOljva5HDelCdBvunaWtUO/+CdKIgsdbQGbqc1aWmG6gr+ShQk4X3KzeAA91AFmkJOR6Jv69lUTm6Uo9AKs1JtuVZsOa1aoOmfApohqFuXsRBNXlg=
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organisation: dwenzel-github
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

before_script:
  - composer require typo3/minimal=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
- >
  if [[ "$COVERAGE" != "1" ]]; then
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
  fi

- >
  if [[ "$COVERAGE" == "1" ]]; then
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c Tests/Build/UnitTests.xml Tests/Unit/ \
    --coverage-clover .Build/log/coverage/clover.xml \
    --log-junit .Build/log/junit.xml
    rm -rf .Build/vendor/ .Build/Web/ .Build/bin/
    sonar-scanner -Dproject.settings=.sonar-project.properties
  fi
  echo;
  export typo3DatabaseName="typo3";
  export typo3DatabaseHost="localhost";
  export typo3DatabaseUsername="root";
  export typo3DatabasePassword="";
  find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --coverage-clover=.Build/log/coverage/{}functionaltest.clover --colors  -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}'

after_success:
- >
  if [[ "$COVERAGE" == "1" ]]; then
    bash <(curl -s https://codecov.io/bash) -s ./.Build/log/coverage/Tests/Functional/ -f "*.clover" -F functional
    bash <(curl -s https://codecov.io/bash) -B $TRAVIS_BRANCH
  fi
